---
name: CI

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python latest
        uses: actions/setup-python@v2
        with:
          python-version: latest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Linter
        run: |
          pipenv run ansible-lint roles setup_infra.yml
